main/urls.py
from django.urls import path

from . import views #this will be usefull when we want to include certain urls,instead of hardcoding it we can use views.

app_name="main"

urlpatterns = [
   path("",views.homepage,name="homepage"),#call the homepage fucntion in views.py
   path("register/",views.register,name="register"),
   path("logout/",views.logout_user,name="logout"),
   path("login/",views.login_user,name="login"),
   path("viewlist/",views.viewlist,name="viewlist"),
    path("list/", views.book_list, name="book_list"),
   path("new/", views.book_create, name="book_new"),
   path("edit/<int:pk>/", views.book_update, name="book_edit"),
   path("delete/<int:pk>/", views.book_delete, name="book_delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('',include('main.urls')),

    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
import datetime

from django.http import request
from django.contrib.auth import get_user_model


from django import forms

def get_now():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
def get_now2():
    return datetime.datetime.now()


COLOR_CHOICES = (
    ('yes','YES'),
    ('no','NO'),
)

YES_NO=('COMLPLETED','NOT ')
# Create your models here.
User=get_user_model()
class MainTodo(models.Model):
    todo_deadline = models.DateTimeField(default=get_now2)
    #todo_deadline = models.DateTimeField(datetime.datetime.now())
    todo_title = models.CharField(max_length=200)
    todo_content = models.TextField()
    #todo_status = models.CharField(max_length=10)
    todo_status = models.CharField(max_length=3, choices=COLOR_CHOICES, default='no')
    todo_username = models.ForeignKey(User, on_delete=models.CASCADE,default=3)

main/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import MainTodo

#for register
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
	#re
from django.shortcuts import redirect

#for message in form
from django.contrib import messages
#custom user form
from .myforms import NewUserForm



# Create your views here.
def homepage(request):
	return render(request=request,template_name="main/home.html")


def viewlist(request):
	#return HttpResponse("wow this is awesome")
	print(request.user.id," \t",request.user)
	return render(request=request,template_name="main/viewlist.html",context={"todos":MainTodo.objects.filter(todo_username=request.user.id)})

def register(request):

	if request.method=="POST":
		form =NewUserForm(request.POST)
		if form.is_valid() :
			user=form.save()
			username=form.cleaned_data.get('username')
			messages.success(request,f"New Account Created :{username}")
			#user is created so loginthe user
			login(request,user)
			messages.info(request,f"You are now logged in as :{username}")
			return redirect("main:homepage") # u could write like redirect("app_name:name_in_path")
		else:

			for err in form.error_messages:
				messages.error(request,f"{err}:{form.error_messages[err]}")

	form =NewUserForm()
	return render(request=request,template_name="main/register.html",context={"form":form})

def logout_user(request):
	logout(request)
	messages.info(request,"You are logged out ")
	return redirect("main:homepage")

#we import authenticationForm for login
def login_user(request):
	if request.method=="POST":
		form=AuthenticationForm(request,data=request.POST)
		if form.is_valid() :
			username=form.cleaned_data.get('username')
			password=form.cleaned_data.get('password')
			user=authenticate(username=username,password=password)
			if user is not None:
				messages.success(request,f"logged in as :{username}")
				#user is created so loginthe user
				login(request,user)
				return redirect("main:homepage") # u could write like redirect("app_name:name_in_path")
			else:
				messages.error(request,f"Invalid username or password ")
	form = AuthenticationForm()
	return render(request = request,template_name = "main/login.html",context={"form":form})


from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django import forms
from .models import MainTodo

class BookForm(forms.ModelForm):
	class Meta:
		model = MainTodo
		widgets={'todo_username':forms.HiddenInput()}

		fields = ['todo_title','todo_deadline','todo_content','todo_status']
		

def book_list(request, template_name='main/book_list.html'):
    #book = MainTodo.objects.all()
    book = MainTodo.objects.filter(todo_username=request.user.id)
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='main/book_form.html'):
	print("hello ",request.user.id,"name ",request.user.username)

	form = BookForm(request.POST or None)
	if form.is_valid():
		data = form.save(commit=False)
		data.todo_username=request.user
		print("field ","hello ",request.user.id,"name ",request.user.username)
		data.save()
		#form.save()
		return redirect('main:book_list')
	return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='main/book_form.html'):
    book= get_object_or_404(MainTodo, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('main:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='main/book_confirm_delete.html'):
    book= get_object_or_404(MainTodo, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('main:book_list')
    return render(request, template_name, {'object':book})

main/templates/main/book_confirm_delete.html
{% extends 'main/header.html' %}

{% block content %}

<h2><a href="{% url 'main:book_list' %}">Books FBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

main/templates/main/book_form.html
{% extends 'main/header.html' %}

{% block content %}

<h2>Todo Task</h2>
<B>note: input for Todo deadline must be of the form YYYY-MM-DD hh:mm:ss 
example: 2019-03-18 23:00:00</B>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
<script>
        document.getElementById("id_todo_status").style.display="inline-block";
       document.getElementById("id_todo_status").style.color="red";
   </script>

{% endblock %}

main/templates/main/book_list.html
{% extends 'main/header.html' %}

{% block content %}

<!-- <h2><a href="{% url 'main:book_list' %}">Books FBV</a></h2> -->

<!-- <ul>
    {% for book in object_list %}
    <li>{{ book.todo_title }} {{ book.todo_deadline }}{{ book.todo_content }} {{ book.todo_status }}
    <a href="{% url 'main:book_edit' book.id %}">edit</a>
    <a href="{% url 'main:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul> -->


<strong><a href="{% url 'main:book_new' %}">New Todo</a></strong>

<div class="row">

		{% for book in object_list %}

		<div class="col s12 m6">
		  <div class="card blue-grey darken-1">
		    <div class="card-content white-text">
		      <span class="card-title">{{book.todo_title}}</span>
              <p style="font-style:70% ">{{book.todo_deadline}}</p>
              <p>{{book.todo_status}}</p>
              <p>{{book.todo_content}}</p>
		    </div>
		    <div class="card-action">
						<a href="{% url 'main:book_edit' book.id %}">EDIT</a>
						<a href="{% url 'main:book_delete' book.id %}">DELETE</a>
		      
		    </div>
		  </div>
		</div>
		{% endfor %}

  </div>






{% endblock %}

main/templates/main/header.html
<head>

  {% load static %}

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  
</head>

<body>

	{% include "main/includes/nav.html" %}


  {% include "main/includes/messages.html" %}

  	<div class="container" style="display: block;">
  		<br>
		{% block content %}
		{% endblock %}

  </div>


</body>

main/templates/main/home.html
{% extends 'main/header.html' %}


{% block content %}

	<div class="row">
			<font size="4.5">
		<p>hi this a todo applications
		<ul>database used :postgres</ul>
		<ul>CRUD operations can be performed </ul>
		<ul>appropriate models have been used </ul>
		<ul>REGISTER TO USE THE APP</ul>
		Your each todo task will be display like this
		</p>
		</font>
		<div class="row">
		
				<div class="col s12 m6">
				  <div class="card blue-grey darken-1">
					<div class="card-content white-text">
					  <span class="card-title">todo_title</span>
					  <p style="font-style:70% ">todo_deadline</p>
					  <p>todo_content</p>
					</div>
					<div class="card-action">
								<a href="#">STATUS_COMPLETED:</a>
								<a href="#">yes or no </a>
					  
					</div>
				  </div>
				</div>
		
		  </div>
	<p>
	PLEASE NOTE THAT secret key has been set to "" SECRET_KEY = ''
	debug is set to False DEBUG = False
	Since debug is set to False ,allowed_hosts is set as: ALLOWED_HOSTS = ['localhost', '127.0.0.1']	
	</p>
  </div>
            
{% endblock %}

main/templates/main/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'%}
            <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
        {% elif message.tags == 'info'%}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
        {% elif message.tags == 'warning'%}
            <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
        {% elif message.tags == 'error'%}
            <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
        {% endif %}
    {% endfor %}
  {% endif %}

main/templates/main/includes/nav.html
<nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Todo List </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">home</a></li>
            {% if user.is_authenticated %}
                  <li><a href="https://github.com/mmaashraf">Github</a></li>
                 <li><a href="#">{{user.username|title}}</a></li>
                 <li><a href="/logout">Logout</a></li>
                 <li><a href="/viewlist">My Todo list</a></li>

                 <li><a href="{% url 'main:book_list' %}">CRUD Todo list</a></li>
                
            {% else %}
                <li><a href="/login">Login</a></li>
                <li><a href="/register">Register</a></li>

            {% endif %}
            
    
    
    
          </ul>
        </div>
      </nav>

main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}} <!--show the form elements as paragrahps p ,list ul or ol etc  -->


		<button class="btn" type="submit"> Login</button>

	</form>

	if u don't have an account, <a href="/register">Register</a> instead.
{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}} <!--show the form elements as paragrahps p ,list ul or ol etc  -->


		<button class="btn" type="submit"> register</button>

	</form>

	if u already have an account, <a href="/login">login</a> instead.
{% endblock %}

main/templates/main/viewlist.html
{% extends 'main/header.html' %}


{% block content %}
    these are the today's objectives/tasks


	<div class="row">

		{% for tut in todos %}

		<div class="col s12 m6">
		  <div class="card blue-grey darken-1">
		    <div class="card-content white-text">
		      <span class="card-title">{{tut.todo_title}}</span>
		      <p style="font-style:70% ">{{tut.todo_deadline}}</p>
		      <p>{{tut.todo_content|safe}}</p>
		    </div>
		    <div class="card-action">
						<a href="#">STATUS_COMPLETED</a>
						<a href="#">: {{tut.todo_status}}</a>
				



<!-- 
		      <a href="#">STATUS</a>
		      {% if tut.todo_status is not '1' %}
		      <a href="#">COMPLETED</a>
		      {% else %}
		      <a href="#">NOT YET DONE</a>
		      {% endif %} -->
		      
		    </div>
		  </div>
		</div>
		{% endfor %}

  </div>
            
{% endblock %}